model_config:
  model_name: "labram_base_patch200_200"
  ues_abs_pos_emb: true
  attn_drop_rate: 0.0
  auto_resume: false
  batch_size: 512
  clip_grad: null
  dataset: TUA
  device: cuda
  disable_eval_during_finetuning: false
  disable_weight_decay_on_rel_pos_bias: false
  dist_eval: true
  dist_on_itp: false
  dist_url: env://
  drop_rate: 0.0
  drop_path_rate: 0.1
  drop_block_rate: null
  enable_deepspeed: false
  epochs: 50
  eval: false
  finetune: ./checkpoints/labram-base.pth
  init_scale: 0.001
  input_size: 200
  layer_decay: 0.65
  init_values: 0.1
  local_rank: -1
  log_dir: /disks/disk0/meijw/log/align_clip
  lr: 0.0005
  min_lr: 1.0e-06
  model: labram_base_patch200_200
  model_ema: false
  model_ema_decay: 0.9999
  model_ema_force_cpu: false
  model_filter_name: gzp
  model_key: model|module
  model_prefix: ''
  momentum: 0.9
  num_classes: 0
  num_workers: 10
  opt: adamw
  opt_betas: null
  opt_eps: 1.0e-08
  output_dir: ./output_dir
  pin_mem: true
  qkv_bias: false
  recount: 1
  ues_rel_pos_bias: false
  remode: pixel
  reprob: 0.25
  resplit: false
  resume: ''
  robust_test: null
  save_ckpt: true
  save_ckpt_freq: 5
  seed: 0
  smoothing: 0.1
  start_epoch: 0
  update_freq: 1
  use_mean_pooling: true
  warmup_epochs: 5
  warmup_lr: 1.0e-06
  warmup_steps: -1
  weight_decay: 0.05
  weight_decay_end: null
  world_size: 1
